
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hello-urmsone-com-v1beta1-helloservice
  failurePolicy: Fail
  name: mhelloservice.kb.io
  rules:
  - apiGroups:
    - hello.urmsone.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helloservices

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-hello-urmsone-com-v1beta1-helloservice
  failurePolicy: Fail
  name: vhelloservice.kb.io
  rules:
  - apiGroups:
    - hello.urmsone.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helloservices
